### PR TITLE
fix: Generated source files end in .g.cs

### LINKED ISSUE #18: Generated source files should end with .g.cs to mark them as autogenerated
## Source issue  
Long story short: for all our libs that use Expressionify, coverlet does not generate coverage reports anymore. Briefly explained, coverlet does not detect the source generated by Expressionify as generated and won't instrument the assembly, as it doesn't have all the sources.

Why is this an issue with Expressionify?
If the generated source files follow a naming convention, coverlet detects the files as auto generated and magically starts working again. (see https://github.com/coverlet-coverage/coverlet/issues/1084#issuecomment-779030934)

## Fix
The file names simply have to end in `.g.cs` or `.generated.cs`

This naming convention isn't something random invented by coverlet, but is also hidden in plain sight in multiple docs. Examples:
https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview#get-started-with-source-generators
In the tip in point 6:
> It's common to provide an explicit C# file extension such as ".g.cs" or ".generated.cs" for the name. The file name helps identify the file as being source generated.

https://learn.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts
In the "Important"-block
> [...]
> There are four ways a file is marked as generated:
> [...]
> 4. End the file name with .designer.cs, .generated.cs, .g.cs, or .g.i.cs.

### PR DESCRIPTION
**Pull request by jhartmann123**
Fixes #18

### CODE REVIEW

File: src/Clave.Expressionify.Generator/ExpressionifySourceGenerator.cs [hunk 1]
```diff
@@ -59,7 +61,11 @@ private static void Execute(GeneratorExecutionContext context, IEnumerable<Metho
 
                 foreach (var (path, source) in replacedTypes)
                 {
-                    context.AddSource(Path.GetFileNameWithoutExtension(path)+$"_expressionify_{i++}.cs", SourceText.From(source.ToFullString(), Encoding.UTF8));
+                    var sourceCode = NullableDirective + source.ToFullString();
```
Comment (jhartmann123) [inline src/Clave.Expressionify.Generator/ExpressionifySourceGenerator.cs:64]: Note: I'm adding `#nullable enable` to all generated sources, as otherwise the generated code won't compile with the error `CS8669: The annotation for nullable reference types should only be used in code within a '#nullable' annotations context. Auto-generated code requires an explicit '#nullable' directive in source.` (which is a warning, but we have WarningsAsErrors enabled)

Not sure, if this is fine for "legacy" projects where nullable is disabled, as I don't have any bigger old project to test it in, where we also use Expressionify...

Comment (slashP) [reply src/Clave.Expressionify.Generator/ExpressionifySourceGenerator.cs:64]: I'm also not fully sure about old projects, but from all I could find it seemed fine.

File: tests/Clave.Expressionify.Generator.Tests/CodeGeneratorTests.cs [hunk 2]
```diff
@@ -73,7 +84,49 @@ public partial class Nested
             private static System.Linq.Expressions.Expression<System.Func<int, int>> Foo_Expressionify_0 { get; } = (int x) => 8;
         }
     }
-}", TestName = "File scoped namespace")]
+}", TestName = "Nested class")]
```
Comment (slashP) [inline tests/Clave.Expressionify.Generator.Tests/CodeGeneratorTests.cs:87]: I personally find these test cases a bit hard to read, but that's not specifically something introduced here. Tried a bit with TestCaseSource, but never got to anything I was happy with.
